edi_af_aisf_ash_kom AFC-1310: new module that updates all employees c…
vertelab/odoo-edi pull request #75
Opened 2021-02-08 14:56 UTC by SebastianGieser-Vertel

…onnected to all departments

2021-02-09 07:58 UTC, arturchilangwa-vertel requested changes

2021-02-09 07:58 UTC, arturchilangwa-vertel commented on edi_af_aisf_ash_kom/__manifest__.py
> +# vim:expandtab:smartindent:tabstop=4s:softtabstop=4:shiftwidth=4:
Do we need config for Vim?

2021-02-09 07:58 UTC, arturchilangwa-vertel commented on edi_af_aisf_ash_kom/data/edi_route_data.xml
> +<openerp>
Is this not old style tags? Should it not be `<odoo/>`.

2021-02-09 07:58 UTC, arturchilangwa-vertel commented on edi_af_aisf_ash_kom/models/edi_route.py
> +_logger = logging.getLogger(__name__)
Unused logger that can be removed

2021-02-09 07:58 UTC, arturchilangwa-vertel commented on edi_af_aisf_ash_kom/messages/af_aisf_ash_kom_get_all.py
> +
Unused logger that can be removed

2021-02-09 10:21 UTC, SebastianGieser-Vertel commented on edi_af_aisf_ash_kom/messages/af_aisf_ash_kom_get_all.py
> +
made some changes, now it's used

2021-02-10 10:46 UTC, arturchilangwa-vertel approved these changes

2021-02-10 10:47 UTC, merged