12.0 afc 1950 Implementation of BOS V2 api
vertelab/odoo-edi pull request #87
Opened 2021-04-22 13:29 UTC by draal-af

2021-04-22 14:46 UTC, nils-vertel requested changes

2021-04-22 14:46 UTC, nils-vertel commented on edi_af_ais_bos/__manifest__.py
> +    'description': """ """,
Add whats new in this version here

2021-04-22 14:46 UTC, nils-vertel commented on edi_af_ais_bos/data/edi_route_data.xml
> +</openerp>
Missing newline at end of file

2021-04-22 14:46 UTC, nils-vertel commented on edi_af_ais_bos/data/edi_route_data.xml
> +<openerp>
Should be odoo?

2021-04-22 14:46 UTC, nils-vertel commented on edi_af_ais_bos/messages/af_get_bos.py
> +from odoo import models, fields, api, _
Imports are wrongly ordered:

- Python standard lib
- Third party
- Own imports
Separate each group with a single new line, Sort each import within a group alphabetically

2021-04-22 14:46 UTC, nils-vertel commented on edi_af_ais_bos/messages/af_get_bos.py
> +        _logger.warning("KROM CHECK UNPACK")
Should this really be on Warning level, this should be info or debug IMHO

2021-04-22 14:46 UTC, nils-vertel commented on edi_af_ais_bos/messages/af_get_bos.py
> +            else:
Should we do something here?
As it is now the else clause can be removed

2021-04-22 14:46 UTC, nils-vertel commented on edi_af_ais_bos/messages/af_get_bos.py
> +                raise Warning("KROM: Attached record is not an res.partner'! {model}".format(
Warning is depricated use UserError instead

2021-04-22 14:46 UTC, nils-vertel commented on edi_af_ais_bos/messages/af_get_bos.py
> +                raise Warning("Postcode field is empty or invalid")
See above

2021-04-22 14:46 UTC, nils-vertel commented on edi_af_ais_bos/models/ediroute.py
> +from odoo import models, fields, api, _
Wrongly sorted imports
Is all of these imports used?
Consider only keeping the standard imports (from odoo import models, fields, api, _
Write) (logging)

2021-04-22 14:46 UTC, nils-vertel commented on edi_af_ais_bos/views/edi_af_ais_bos_views.xml
> +</odoo>
No new line at end of file

2021-04-22 14:46 UTC, nils-vertel commented on edi_route_ipf/models/edi_route.py
> +        _logger.debug("ipf_rest.get() message.edi_type: %s")
Why the additional logger row here?

2021-04-29 14:42 UTC, daerio commented
replaced with other PR

2021-04-29 14:42 UTC, closed without merging